//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGlobalPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametreler
    {
        public long LOGICALREF { get; set; }
        public string FirmaKodu { get; set; }
        public string IsYeriKodu { get; set; }
        public string DepoKodu { get; set; }
        public string SatisSiparisKaynagi { get; set; }
        public string HareketKodu { get; set; }
        public string SatisSiparisBelgeNoBaslangici { get; set; }
        public string SatisSiparisBaslangicNo { get; set; }
        public string SatisSiparisiKdvDurumu { get; set; }
        public string TeklifKaynagi { get; set; }
        public string TeklifHareketKod { get; set; }
        public string TeklifBelgeNoBaslangici { get; set; }
        public string TeklifBaslangicNo { get; set; }
        public string TeklifKdvDurumu { get; set; }
    }
}
