//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGlobalPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetBasligi
    {
        public long LOGICALREF { get; set; }
        public string IsYeriKodu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string HareketKodu { get; set; }
        public string CariKodu { get; set; }
        public string CariAdi { get; set; }
        public string ParaBirimi { get; set; }
        public string KurSecenegi { get; set; }
        public string OdemeSekli { get; set; }
        public string SevkIli { get; set; }
        public string SevkIlce { get; set; }
        public string SevkAdresi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public string Ekleyen { get; set; }
        public string OdemePlani { get; set; }
    }
}
