//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGlobalPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciYetkileri
    {
        public long LOGICALREF { get; set; }
        public Nullable<long> KullaniciId { get; set; }
        public Nullable<bool> SiparisOluturabilirMi { get; set; }
        public Nullable<bool> SiparisleriGorebilirMi { get; set; }
        public Nullable<bool> IrsaliyeleriGorebilirMi { get; set; }
        public Nullable<bool> HesapEkstresiniGorebilirMi { get; set; }
        public Nullable<bool> FaturalariGorebilirMi { get; set; }
    }
}
