//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGlobalPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewGlobalDBEntities : DbContext
    {
        public NewGlobalDBEntities()
            : base("name=NewGlobalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<KullaniciYetkileri> KullaniciYetkileris { get; set; }
        public virtual DbSet<Parametreler> Parametrelers { get; set; }
        public virtual DbSet<SepetBasligi> SepetBasligis { get; set; }
        public virtual DbSet<SepetIcerik> SepetIceriks { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
    }
}
