//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGlobalPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int LOGICALREF { get; set; }
        public string TokenAdi { get; set; }
        public string Token1 { get; set; }
        public string Security { get; set; }
        public string TokenType { get; set; }
        public Nullable<System.DateTime> OlusmaTarihi { get; set; }
        public Nullable<System.DateTime> SonGecerlilikTarihi { get; set; }
    }
}
