using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewGlobalPortal.Models.Class
{
   

    public class UyumUrunDetaylari
    {
        public int statusCode { get; set; }
        public string message { get; set; }
        public UyumUrunDetaylariResult result { get; set; }
    }

    public class UyumUrunDetaylariResult
    {
        public Item_M[] iteM_M { get; set; }
        public Item_UNIT[] iteM_UNIT { get; set; }
        public object[] iteM_ATTRIBUTE { get; set; }
        public object[] iteM_ALTER { get; set; }
        public object[] iteM_KIT { get; set; }
        public object[] iteM_SUPPLY_RANGE { get; set; }
        public object[] iteM_MODEL { get; set; }
        public Item_BWH[] iteM_BWH { get; set; }
        public Item_BRANCH[] iteM_BRANCH { get; set; }
        public Item_TAX[] iteM_TAX { get; set; }
        public Item_BARCODE[] iteM_BARCODE { get; set; }
        public object[] iteM_GROUP_REL { get; set; }
        public object[] iteM_DIM1 { get; set; }
        public object[] iteM_DIM2 { get; set; }
        public object[] iteM_DIM_MTX { get; set; }
    }

    public class Item_M
    {
        public string itemKitCollection { get; set; }
        public string itemDetailAttributesCollection { get; set; }
        public string itemSupplyRangeCollection { get; set; }
        public string itemModelCollection { get; set; }
        public string isAsset { get; set; }
        public string toleranceRate { get; set; }
        public string toleranceRateType { get; set; }
        public string assetGrpId { get; set; }
        public string qrTempMId { get; set; }
        public string qrDesc { get; set; }
        public string qrCode { get; set; }
        public string assetGrpCode { get; set; }
        public string assetGrpDesc { get; set; }
        public string cccnId { get; set; }
        public string cccnCode { get; set; }
        public string cccnDesc { get; set; }
        public string brandCode { get; set; }
        public string brandDesc { get; set; }
        public string supplyTypeCode { get; set; }
        public string supplyClass { get; set; }
        public string countryOrgCode { get; set; }
        public string catCode2 { get; set; }
        public string catDescription2 { get; set; }
        public string catCode1 { get; set; }
        public string catDescription1 { get; set; }
        public string volumeUnitCode { get; set; }
        public string densityUnitCode { get; set; }
        public string weightUnitCode { get; set; }
        public string metricUnitCode { get; set; }
        public string freeUnitCode { get; set; }
        public string freeUnitCode2 { get; set; }
        public string purchaseUnitCode { get; set; }
        public string salesUnitCode { get; set; }
        public string bomUnitCode { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string bomUnitId { get; set; }
        public string curCode { get; set; }
        public string curId { get; set; }
        public string ispassive { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public string description3 { get; set; }
        public string description4 { get; set; }
        public string description5 { get; set; }
        public string description6 { get; set; }
        public string description7 { get; set; }
        public string description8 { get; set; }
        public string itemCode { get; set; }
        public string itemCode2 { get; set; }
        public string itemName { get; set; }
        public string itemGrp1Id { get; set; }
        public string itemGrp2Id { get; set; }
        public string itemGrp3Id { get; set; }
        public string itemGrp4Id { get; set; }
        public string itemGrp5Id { get; set; }
        public string itemGrp6Id { get; set; }
        public string itemGrp7Id { get; set; }
        public string itemGrp8Id { get; set; }
        public string itemGrpCode1 { get; set; }
        public string itemGrpCode2 { get; set; }
        public string itemGrpCode3 { get; set; }
        public string itemGrpCode4 { get; set; }
        public string itemGrpCode5 { get; set; }
        public string itemGrpCode6 { get; set; }
        public string itemGrpCode7 { get; set; }
        public string itemGrpCode8 { get; set; }
        public string purchaseUnitId { get; set; }
        public string salesUnitId { get; set; }
        public string unitCode { get; set; }
        public string unitId { get; set; }
        public string bwhItemCollection { get; set; }
        public string bwhItemCollection2 { get; set; }
        public string branchItemCollection { get; set; }
        public string itemLangCollection { get; set; }
        public string itemUnitCollection { get; set; }
        public string itemTaxCollection { get; set; }
        public string itemAlterCollection { get; set; }
        public string itemBarcodeCollection { get; set; }
        public string itemGroupRelCollection { get; set; }
        public string itemAttributeCollection { get; set; }
        public string abcCode { get; set; }
        public string aboriginalCostFactor { get; set; }
        public string addDate01 { get; set; }
        public string addDate02 { get; set; }
        public string addDate03 { get; set; }
        public string addDate04 { get; set; }
        public string addDate05 { get; set; }
        public string addDate06 { get; set; }
        public string addDate07 { get; set; }
        public string addDate08 { get; set; }
        public string addDate09 { get; set; }
        public string addDate10 { get; set; }
        public string addDec01 { get; set; }
        public string addDec02 { get; set; }
        public string addDec03 { get; set; }
        public string addDec04 { get; set; }
        public string addDec05 { get; set; }
        public string addDec06 { get; set; }
        public string addDec07 { get; set; }
        public string addDec08 { get; set; }
        public string addDec09 { get; set; }
        public string addDec10 { get; set; }
        public string addString01 { get; set; }
        public string addString02 { get; set; }
        public string addString03 { get; set; }
        public string addString04 { get; set; }
        public string addString05 { get; set; }
        public string addString06 { get; set; }
        public string addString07 { get; set; }
        public string addString08 { get; set; }
        public string addString09 { get; set; }
        public string addString10 { get; set; }
        public string brandId { get; set; }
        public string catCode1Id { get; set; }
        public string catCode2Id { get; set; }
        public string countryOfOrigin { get; set; }
        public string density { get; set; }
        public string densityUnitId { get; set; }
        public string depth { get; set; }
        public string freeUnitId { get; set; }
        public string freeUnitId2 { get; set; }
        public string grossDepth { get; set; }
        public string grossHeight { get; set; }
        public string grossWeight { get; set; }
        public string grossWidth { get; set; }
        public string height { get; set; }
        public string isphantom { get; set; }
        public string isConfigurable { get; set; }
        public string isserialTrack { get; set; }
        public string itemName2 { get; set; }
        public string leadTime { get; set; }
        public string manufacturerCode { get; set; }
        public string metricUnitId { get; set; }
        public string netWeight { get; set; }
        public string noteLarge { get; set; }
        public string noteLarge2 { get; set; }
        public string noteLarge3 { get; set; }
        public string noteLarge4 { get; set; }
        public string oldItemCode { get; set; }
        public string orderPeriod { get; set; }
        public string originalCode { get; set; }
        public string productivity { get; set; }
        public string qtyMaxInv { get; set; }
        public string qtyMaxPo { get; set; }
        public string qtyMaxSo { get; set; }
        public string qtyMinInv { get; set; }
        public string qtyMinPo { get; set; }
        public string qtyMinSo { get; set; }
        public string qtyOptimumOrder { get; set; }
        public string qtyOrderLevel { get; set; }
        public string qtyOrderLot { get; set; }
        public string safetyLeadTime { get; set; }
        public string shelfLife { get; set; }
        public string sourceApp { get; set; }
        public string sourceApp2 { get; set; }
        public string sourceApp3 { get; set; }
        public string sourceDId { get; set; }
        public string sourceMId { get; set; }
        public string supplyTypeId { get; set; }
        public string tareWeight { get; set; }
        public string toleranceMaxPo { get; set; }
        public string toleranceMaxSo { get; set; }
        public string toleranceMinPo { get; set; }
        public string toleranceMinSo { get; set; }
        public string volume { get; set; }
        public string volumeUnitId { get; set; }
        public string weightUnitId { get; set; }
        public string width { get; set; }
        public string itemDueDiscGrpId { get; set; }
        public string itemDueDiscGrpCode { get; set; }
        public string itemDueDiscGrpDesc { get; set; }
        public string itemPriceGrpCode { get; set; }
        public string itemPriceGrpDesc { get; set; }
        public string itemPriceGrpId { get; set; }
        public string pItemDueDiscGrpId { get; set; }
        public string pItemDueDiscGrpCode { get; set; }
        public string pItemDueDiscGrpDesc { get; set; }
        public string pItemPriceGrpCode { get; set; }
        public string pItemPriceGrpDesc { get; set; }
        public string pItemPriceGrpId { get; set; }
        public string entityCode { get; set; }
        public string entityId { get; set; }
        public string entityName { get; set; }
        public string qtyFixedOrder { get; set; }
        public string manMergePeriod { get; set; }
        public string itemClassCode { get; set; }
        public string qtyOptimumMan { get; set; }
        public string invItemClass { get; set; }
        public string itemClassCodeDesc { get; set; }
        public string itemClassId { get; set; }
        public string itemClassGroup { get; set; }
        public string qtyMaxMan { get; set; }
        public string qtyMinMan { get; set; }
        public string qtyManLot { get; set; }
        public string qtyRemanPoint { get; set; }
        public string manLeadTime { get; set; }
        public string manSafetyLeadTime { get; set; }
        public string qtyFixedMan { get; set; }
        public string planningCode { get; set; }
        public string isUseInMps { get; set; }
        public string manPolicyType { get; set; }
        public string manFenceDuration { get; set; }
        public string manMessageDuration { get; set; }
        public string orderPolicy { get; set; }
        public string purchaseFenceDuration { get; set; }
        public string purchaseMessageDuration { get; set; }
        public string salesSafetyLeadTime { get; set; }
        public string salesFenceDuration { get; set; }
        public string salesMessageDuration { get; set; }
        public string consumptionUnitId { get; set; }
        public string isNotDemountable { get; set; }
        public string consumptionUnit { get; set; }
        public string doNotWorderMaterialTrnfer { get; set; }
        public string doNotConsumeInWorder { get; set; }
        public string doCollectiveTransfer { get; set; }
        public string collectiveTransferQuantity { get; set; }
        public string collectiveTransferUnitId { get; set; }
        public string collectiveTransferUnit { get; set; }
        public string itemLineType { get; set; }
        public string refItemId { get; set; }
        public string refItemName { get; set; }
        public string refItemCode { get; set; }
        public string itemGroupTreeDId { get; set; }
        public string categories10Id { get; set; }
        public string categories11Id { get; set; }
        public string categories12Id { get; set; }
        public string categories13Id { get; set; }
        public string categories14Id { get; set; }
        public string categories15Id { get; set; }
        public string categories16Id { get; set; }
        public string categories17Id { get; set; }
        public string categories18Id { get; set; }
        public string categories19Id { get; set; }
        public string categories1Id { get; set; }
        public string categories20Id { get; set; }
        public string categories2Id { get; set; }
        public string categories3Id { get; set; }
        public string categories4Id { get; set; }
        public string categories5Id { get; set; }
        public string categories6Id { get; set; }
        public string categories7Id { get; set; }
        public string categories8Id { get; set; }
        public string categories9Id { get; set; }
        public string categories10Code { get; set; }
        public string categories11Code { get; set; }
        public string categories12Code { get; set; }
        public string categories13Code { get; set; }
        public string categories14Code { get; set; }
        public string categories15Code { get; set; }
        public string categories16Code { get; set; }
        public string categories17Code { get; set; }
        public string categories18Code { get; set; }
        public string categories19Code { get; set; }
        public string categories1Code { get; set; }
        public string categories20Code { get; set; }
        public string categories2Code { get; set; }
        public string categories3Code { get; set; }
        public string categories4Code { get; set; }
        public string categories5Code { get; set; }
        public string categories6Code { get; set; }
        public string categories7Code { get; set; }
        public string categories8Code { get; set; }
        public string categories9Code { get; set; }
        public string categories10Desc { get; set; }
        public string categories11Desc { get; set; }
        public string categories12Desc { get; set; }
        public string categories13Desc { get; set; }
        public string categories14Desc { get; set; }
        public string categories15Desc { get; set; }
        public string categories16Desc { get; set; }
        public string categories17Desc { get; set; }
        public string categories18Desc { get; set; }
        public string categories19Desc { get; set; }
        public string categories1Desc { get; set; }
        public string categories20Desc { get; set; }
        public string categories2Desc { get; set; }
        public string categories3Desc { get; set; }
        public string categories4Desc { get; set; }
        public string categories5Desc { get; set; }
        public string categories6Desc { get; set; }
        public string categories7Desc { get; set; }
        public string categories8Desc { get; set; }
        public string categories9Desc { get; set; }
        public string image1 { get; set; }
        public string itemGroupTreePath { get; set; }
        public string dim_Type1 { get; set; }
        public string dim_Type2 { get; set; }
        public string dimInfo { get; set; }
        public string isMtxChangable { get; set; }
        public string isMontage { get; set; }
        public string scrapTraType { get; set; }
        public string defaultAsortMode { get; set; }
        public string defaultDim2Empty { get; set; }
        public string charCodeMCode { get; set; }
        public string charCodeMId { get; set; }
        public string charCodeMName { get; set; }
        public string qtyNegativeBalance { get; set; }
        public string defaultTaxId { get; set; }
        public string defaultTaxDesc { get; set; }
        public string defaultTaxRate { get; set; }
        public string defaultTaxCode { get; set; }
        public string isKitUpdateable { get; set; }
        public string woSoOverPercent { get; set; }
        public string isModel { get; set; }
        public string modelItemId { get; set; }
        public string contractGroupId { get; set; }
        public string contractGroupCode { get; set; }
        public string contractGroupDesc { get; set; }
        public string itemDim1Collection { get; set; }
        public string itemDim2Collection { get; set; }
        public string itemDimMtxCollection { get; set; }
        public string qtyPrecision { get; set; }
        public string deleteImage { get; set; }
        public string dontApplyDisc { get; set; }
        public string profitMargin { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

    public class Item_UNIT
    {
        public string unitTransform { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string depth { get; set; }
        public string height { get; set; }
        public string itemId { get; set; }
        public string lineNo { get; set; }
        public string rate { get; set; }
        public string rate2 { get; set; }
        public string unit2Id { get; set; }
        public string unitCode { get; set; }
        public string unitDesc { get; set; }
        public string unitCode2 { get; set; }
        public string unitDesc2 { get; set; }
        public string unitId { get; set; }
        public string volume { get; set; }
        public string weight { get; set; }
        public string width { get; set; }
        public string itemCode { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

    public class Item_BWH
    {
        public string lotId { get; set; }
        public string lotCode { get; set; }
        public string colorId { get; set; }
        public string colorCode { get; set; }
        public string qualityId { get; set; }
        public string qualityCode { get; set; }
        public string packageTypeId { get; set; }
        public string packageTypeCode { get; set; }
        public string itemAttribute1Id { get; set; }
        public string itemAttributeCode1 { get; set; }
        public string itemAttribute2Id { get; set; }
        public string itemAttributeCode2 { get; set; }
        public string itemAttribute3Id { get; set; }
        public string itemAttributeCode3 { get; set; }
        public string freePrmMCode { get; set; }
        public string freePrmMId { get; set; }
        public string freeSecMCode { get; set; }
        public string freeSecMId { get; set; }
        public string taxId { get; set; }
        public string taxRate { get; set; }
        public string transferByRequestQty { get; set; }
        public string qtyAfterSalesPurchase { get; set; }
        public string qtyAvailability { get; set; }
        public string toleranceRateByItem { get; set; }
        public string defaultPackageTypeId { get; set; }
        public string defaultPackageTypeCode { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string abtActCode { get; set; }
        public string abtActDesc { get; set; }
        public string abtActId { get; set; }
        public string abtBudgetCode { get; set; }
        public string abtBudgetDesc { get; set; }
        public string abtBudgetId { get; set; }
        public string itemGroupTreeDId { get; set; }
        public string branchCode { get; set; }
        public string branchId { get; set; }
        public string branchItemId { get; set; }
        public string bwhId { get; set; }
        public string coCode { get; set; }
        public string coId { get; set; }
        public string gainLoss { get; set; }
        public string isnegative { get; set; }
        public string ispassive { get; set; }
        public string itemCode { get; set; }
        public string itemClassId { get; set; }
        public string oldItemCode { get; set; }
        public string originalCode { get; set; }
        public string manufacturerCode { get; set; }
        public string itemBrandId { get; set; }
        public string brandCode { get; set; }
        public string itemId { get; set; }
        public string iaccIntgTypeCodeId { get; set; }
        public string itemAccIntgCode { get; set; }
        public string qtyMaxInv { get; set; }
        public string qtyMaxPo { get; set; }
        public string qtyMaxSo { get; set; }
        public string qtyMinInv { get; set; }
        public string qtyMinPo { get; set; }
        public string qtyMinSo { get; set; }
        public string qtyPo { get; set; }
        public string qtyPrm { get; set; }
        public string qtySo { get; set; }
        public string qtyFreePrm { get; set; }
        public string qtyFreeSec { get; set; }
        public string toleranceMaxPo { get; set; }
        public string toleranceMaxSo { get; set; }
        public string toleranceMinPo { get; set; }
        public string toleranceMinSo { get; set; }
        public string whouseCode { get; set; }
        public string whouseName { get; set; }
        public string whouseId { get; set; }
        public string itemName { get; set; }
        public string itemName2 { get; set; }
        public string netWeight { get; set; }
        public string defaultAsortMode { get; set; }
        public string amtCost { get; set; }
        public string amtIn { get; set; }
        public string qtyIn { get; set; }
        public string qtyOnRoad { get; set; }
        public string unitPrice { get; set; }
        public string amt { get; set; }
        public string qty { get; set; }
        public string unitCode { get; set; }
        public string unitId { get; set; }
        public string branchDesc { get; set; }
        public string coDesc { get; set; }
        public string whouseDesc { get; set; }
        public string acc1Id { get; set; }
        public string acc2Id { get; set; }
        public string acc3Id { get; set; }
        public string acc4Id { get; set; }
        public string acc5Id { get; set; }
        public string acc6Id { get; set; }
        public string acc7Id { get; set; }
        public string acc8Id { get; set; }
        public string acc9Id { get; set; }
        public string acc1Code { get; set; }
        public string acc1Desc { get; set; }
        public string acc2Code { get; set; }
        public string acc2Desc { get; set; }
        public string acc3Code { get; set; }
        public string acc3Desc { get; set; }
        public string acc4Code { get; set; }
        public string acc4Desc { get; set; }
        public string acc5Code { get; set; }
        public string acc5Desc { get; set; }
        public string acc6Code { get; set; }
        public string acc6Desc { get; set; }
        public string acc7Code { get; set; }
        public string acc7Desc { get; set; }
        public string acc8Code { get; set; }
        public string acc8Desc { get; set; }
        public string acc9Code { get; set; }
        public string acc9Desc { get; set; }
        public string isscraptWhouse { get; set; }
        public string isReworkWhouse { get; set; }
        public string isOutsideWhouse { get; set; }
        public string outsideEntityId { get; set; }
        public string isopenToInternet { get; set; }
        public string isDefault { get; set; }
        public string whousePGrpId { get; set; }
        public string qtySumReserve { get; set; }
        public string qtySumMaterialReserve { get; set; }
        public string qtyAfterReserve { get; set; }
        public string qtyReserve { get; set; }
        public string catCode1Id { get; set; }
        public string catCode1 { get; set; }
        public string catDescription1 { get; set; }
        public string catCode2Id { get; set; }
        public string catCode2 { get; set; }
        public string catDescription2 { get; set; }
        public string isReserveMaterial { get; set; }
        public string isserialTrack { get; set; }
        public object curCode { get; set; }
        public string curId { get; set; }
        public string itemAvailabilityField { get; set; }
        public string categories10Code { get; set; }
        public string categories11Code { get; set; }
        public string categories12Code { get; set; }
        public string categories13Code { get; set; }
        public string categories14Code { get; set; }
        public string categories15Code { get; set; }
        public string categories16Code { get; set; }
        public string categories17Code { get; set; }
        public string categories18Code { get; set; }
        public string categories19Code { get; set; }
        public string categories1Code { get; set; }
        public string categories20Code { get; set; }
        public string categories2Code { get; set; }
        public string categories3Code { get; set; }
        public string categories4Code { get; set; }
        public string categories5Code { get; set; }
        public string categories6Code { get; set; }
        public string categories7Code { get; set; }
        public string categories8Code { get; set; }
        public string categories9Code { get; set; }
        public string addString01 { get; set; }
        public string addString02 { get; set; }
        public string addString03 { get; set; }
        public string addString04 { get; set; }
        public string addString05 { get; set; }
        public string addString06 { get; set; }
        public string addString07 { get; set; }
        public string addString08 { get; set; }
        public string addString09 { get; set; }
        public string addString10 { get; set; }
        public string addDate01 { get; set; }
        public string addDate02 { get; set; }
        public string addDate03 { get; set; }
        public string addDate04 { get; set; }
        public string addDate05 { get; set; }
        public string addDate06 { get; set; }
        public string addDate07 { get; set; }
        public string addDate08 { get; set; }
        public string addDate09 { get; set; }
        public string addDate10 { get; set; }
        public string addDec01 { get; set; }
        public string addDec02 { get; set; }
        public string addDec03 { get; set; }
        public string addDec04 { get; set; }
        public string addDec05 { get; set; }
        public string addDec06 { get; set; }
        public string addDec07 { get; set; }
        public string addDec08 { get; set; }
        public string addDec09 { get; set; }
        public string addDec10 { get; set; }
        public string dimInfo { get; set; }
        public string isConfigurable { get; set; }
        public string itemAttribute4Id { get; set; }
        public object itemAttributeCode4 { get; set; }
        public string itemAttribute5Id { get; set; }
        public object itemAttributeCode5 { get; set; }
        public string itemAttribute6Id { get; set; }
        public object itemAttributeCode6 { get; set; }
        public string itemAttribute7Id { get; set; }
        public object itemAttributeCode7 { get; set; }
        public string itemAttribute8Id { get; set; }
        public object itemAttributeCode8 { get; set; }
        public string itemAttribute9Id { get; set; }
        public object itemAttributeCode9 { get; set; }
        public string itemAttribute10Id { get; set; }
        public object itemAttributeCode10 { get; set; }
        public string itemAttribute11Id { get; set; }
        public object itemAttributeCode11 { get; set; }
        public string itemAttribute12Id { get; set; }
        public object itemAttributeCode12 { get; set; }
        public string itemAttribute13Id { get; set; }
        public object itemAttributeCode13 { get; set; }
        public string itemAttribute14Id { get; set; }
        public object itemAttributeCode14 { get; set; }
        public string itemAttribute15Id { get; set; }
        public object itemAttributeCode15 { get; set; }
        public string itemAttribute16Id { get; set; }
        public object itemAttributeCode16 { get; set; }
        public string itemAttribute17Id { get; set; }
        public object itemAttributeCode17 { get; set; }
        public string itemAttribute18Id { get; set; }
        public object itemAttributeCode18 { get; set; }
        public string itemAttribute19Id { get; set; }
        public object itemAttributeCode19 { get; set; }
        public string itemAttribute20Id { get; set; }
        public object itemAttributeCode20 { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

    public class Item_BRANCH
    {
        public string itemName { get; set; }
        public string itemName2 { get; set; }
        public string branchDesc { get; set; }
        public string plannerCode { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string aboriginalCostFactor { get; set; }
        public string addDate01 { get; set; }
        public string addDate02 { get; set; }
        public string addDate03 { get; set; }
        public string addDate04 { get; set; }
        public string addDate05 { get; set; }
        public string addDate06 { get; set; }
        public string addDate07 { get; set; }
        public string addDate08 { get; set; }
        public string addDate09 { get; set; }
        public string addDate10 { get; set; }
        public string addDec01 { get; set; }
        public string addDec02 { get; set; }
        public string addDec03 { get; set; }
        public string addDec04 { get; set; }
        public string addDec05 { get; set; }
        public string addDec06 { get; set; }
        public string addDec07 { get; set; }
        public string addDec08 { get; set; }
        public string addDec09 { get; set; }
        public string addDec10 { get; set; }
        public string addString01 { get; set; }
        public string addString02 { get; set; }
        public string addString03 { get; set; }
        public string addString04 { get; set; }
        public string addString05 { get; set; }
        public string addString06 { get; set; }
        public string addString07 { get; set; }
        public string addString08 { get; set; }
        public string addString09 { get; set; }
        public string addString10 { get; set; }
        public string branchCode { get; set; }
        public string branchId { get; set; }
        public string buyerId { get; set; }
        public string catCode1 { get; set; }
        public string catCode2 { get; set; }
        public string catCode1Id { get; set; }
        public string catCode2Id { get; set; }
        public string contactName { get; set; }
        public string coCode { get; set; }
        public string coName { get; set; }
        public string coId { get; set; }
        public string description { get; set; }
        public string description1 { get; set; }
        public string description2 { get; set; }
        public string descriptionGrp1 { get; set; }
        public string descriptionGrp2 { get; set; }
        public string descriptionGrp3 { get; set; }
        public string descriptionGrp4 { get; set; }
        public string descriptionGrp5 { get; set; }
        public string descriptionGrp6 { get; set; }
        public string descriptionGrp7 { get; set; }
        public string descriptionGrp8 { get; set; }
        public string entityCode { get; set; }
        public string entityId { get; set; }
        public string entityName { get; set; }
        public string isnegative { get; set; }
        public string isnotMfg { get; set; }
        public string isnotPurchased { get; set; }
        public string isBomRevNoMondatory { get; set; }
        public string isUseQuality { get; set; }
        public string isnotPOrder { get; set; }
        public string isnotPQuote { get; set; }
        public string isnotPReq { get; set; }
        public string isnotReserved { get; set; }
        public string isnotSold { get; set; }
        public string isnotSOrder { get; set; }
        public string isnotSQuote { get; set; }
        public string ispassive { get; set; }
        public string isserialTrack { get; set; }
        public string isLotMondatory { get; set; }
        public string isColorMondatory { get; set; }
        public string isQualityMondatory { get; set; }
        public string isAttribute1Mondatory { get; set; }
        public string isAttribute2Mondatory { get; set; }
        public string isAttribute3Mondatory { get; set; }
        public string isPackageTypeMondatory { get; set; }
        public string isLotExpDateMondatory { get; set; }
        public string itemCode { get; set; }
        public string branchItemGrp1Id { get; set; }
        public string branchItemGrp2Id { get; set; }
        public string itemGrpCode1 { get; set; }
        public string itemGrpCode2 { get; set; }
        public string itemGrpCode3 { get; set; }
        public string itemGrpCode4 { get; set; }
        public string itemGrpCode5 { get; set; }
        public string itemGrpCode6 { get; set; }
        public string itemGrpCode7 { get; set; }
        public string itemGrpCode8 { get; set; }
        public string branchItemGrp1Code { get; set; }
        public string branchItemGrp2Code { get; set; }
        public string itemId { get; set; }
        public string itemPriceGrpCode { get; set; }
        public string itemPriceGrpId { get; set; }
        public string leadTime { get; set; }
        public string noteLarge { get; set; }
        public string noteLarge2 { get; set; }
        public string noteLarge3 { get; set; }
        public string noteLarge4 { get; set; }
        public string orderPeriod { get; set; }
        public string orderPolicy { get; set; }
        public string plannerId { get; set; }
        public string purchaseUnitCode { get; set; }
        public string planningCode { get; set; }
        public string productivity { get; set; }
        public string routeCode { get; set; }
        public string routeId { get; set; }
        public string salesUnitCode { get; set; }
        public string qtyMaxInv { get; set; }
        public string qtyMaxPo { get; set; }
        public string qtyMaxSo { get; set; }
        public string qtyMinInv { get; set; }
        public string qtyMinPo { get; set; }
        public string qtyMinSo { get; set; }
        public string qtyOptimumOrder { get; set; }
        public string qtyOrderLot { get; set; }
        public string qtyReorderPoint { get; set; }
        public string reservationMethod { get; set; }
        public string safetyLeadTime { get; set; }
        public string salesmanId { get; set; }
        public string salesPersonCode { get; set; }
        public string shelfLife { get; set; }
        public string supplyClass { get; set; }
        public string supplyTypeCode { get; set; }
        public string supplyTypeId { get; set; }
        public string toleranceMaxPo { get; set; }
        public string toleranceMaxSo { get; set; }
        public string toleranceMinPo { get; set; }
        public string toleranceMinSo { get; set; }
        public string unitCode { get; set; }
        public string unitId { get; set; }
        public string whouseCode { get; set; }
        public string whouseId { get; set; }
        public string iaccIntgTypeCodeId { get; set; }
        public string itemAccIntgCode { get; set; }
        public string itemAccIntgDesc { get; set; }
        public string itemDueDiscGrpId { get; set; }
        public string itemDueDiscGrpCode { get; set; }
        public string itemDueDiscGrpDesc { get; set; }
        public string inputWarrantyDay { get; set; }
        public string outputWarrantyDay { get; set; }
        public string warrantyUnitId { get; set; }
        public string warrantyUnitCode { get; set; }
        public string itemClassId { get; set; }
        public string itemClassCode { get; set; }
        public string itemClassCodeDesc { get; set; }
        public string invItemClass { get; set; }
        public string lotPatternMId { get; set; }
        public string consumptionUnitId { get; set; }
        public string isNotDemountable { get; set; }
        public string consumptionUnit { get; set; }
        public string doNotWorderMaterialTrnfer { get; set; }
        public string doNotConsumeInWorder { get; set; }
        public string doCollectiveTransfer { get; set; }
        public string collectiveTransferQuantity { get; set; }
        public string collectiveTransferUnitId { get; set; }
        public string collectiveTransferUnit { get; set; }
        public string bomUnitId { get; set; }
        public string bomUnitCode { get; set; }
        public string itemLineType { get; set; }
        public string isProductSerialTrack { get; set; }
        public string isMaterialSerialTrack { get; set; }
        public string isByProductSerialTrack { get; set; }
        public string configuration { get; set; }
        public string isConfiguration { get; set; }
        public string isConfigurable { get; set; }
        public string dimInfo { get; set; }
        public string isLocNegative { get; set; }
        public string isKitUpdateable { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

    public class Item_TAX
    {
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string countryCode { get; set; }
        public string countryId { get; set; }
        public string endDate { get; set; }
        public string itemId { get; set; }
        public string purchaseSales { get; set; }
        public string startDate { get; set; }
        public string taxId { get; set; }
        public string taxCode { get; set; }
        public string taxRate { get; set; }
        public string taxTypeId { get; set; }
        public string taxTypeEnum { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

    public class Item_BARCODE
    {
        public string barcodeGenerate { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string brandId { get; set; }
        public string attributeGrp1 { get; set; }
        public string attributeGrp2 { get; set; }
        public string attributeGrp3 { get; set; }
        public string barcode { get; set; }
        public string colorCode { get; set; }
        public string colorId { get; set; }
        public string curCode { get; set; }
        public string curId { get; set; }
        public string attrgrDescription1 { get; set; }
        public string attrgrDescription2 { get; set; }
        public string attrgrDescription3 { get; set; }
        public string attrDescription1 { get; set; }
        public string attrDescription2 { get; set; }
        public string attrDescription3 { get; set; }
        public string colorDescription { get; set; }
        public string curDescription { get; set; }
        public string lotDescription { get; set; }
        public string packDescription { get; set; }
        public string qltyDescription { get; set; }
        public string unitDescription { get; set; }
        public string description { get; set; }
        public string itemAttribute1Id { get; set; }
        public string itemAttribute2Id { get; set; }
        public string itemAttribute3Id { get; set; }
        public string itemAttributeCode1 { get; set; }
        public string itemAttributeCode2 { get; set; }
        public string itemAttributeCode3 { get; set; }
        public string itemAttributeName1 { get; set; }
        public string itemAttributeName2 { get; set; }
        public string itemAttributeName3 { get; set; }
        public string itemCode { get; set; }
        public string itemGnlAttribute1Id { get; set; }
        public string gnlAttr1Code { get; set; }
        public string gnlAttr2Code { get; set; }
        public string gnlAttr3Code { get; set; }
        public string itemGnlAttribute2Id { get; set; }
        public string itemGnlAttribute3Id { get; set; }
        public string itemId { get; set; }
        public string itemName { get; set; }
        public string lineNo { get; set; }
        public string lotCode { get; set; }
        public string lotId { get; set; }
        public string packageTypeCode { get; set; }
        public string packageTypeId { get; set; }
        public string qty { get; set; }
        public string qualityCode { get; set; }
        public string qualityId { get; set; }
        public string unitCode { get; set; }
        public string unitId { get; set; }
        public string printQty { get; set; }
        public string invBarcodeTypeId { get; set; }
        public string invBarcodeTypeCode { get; set; }
        public string barcodeTypes { get; set; }
        public string barcodeCountryCode { get; set; }
        public string barcodeCompanyCode { get; set; }
        public string brandCode { get; set; }
        public string defaultAsortMode { get; set; }
        public string oldItemCode { get; set; }
        public string productBarcodeCode { get; set; }
        public string qtyFreePrm { get; set; }
        public string qtyFreeSec { get; set; }
        public string itemAttribute4Id { get; set; }
        public string itemAttributeCode4 { get; set; }
        public string sourceApp { get; set; }
        public string sourceMId { get; set; }
        public string sourceDId { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

}