using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewGlobalPortal.Models.Class
{
    

    public class UyumCariDetaylari
    {
        public int statusCode { get; set; }
        public string message { get; set; }
        public UyumCariDetaylariResult result { get; set; }
        public int pageIndex { get; set; }
        public int pageSize { get; set; }
        public int totalPages { get; set; }
        public int totalCount { get; set; }
    }

    public class UyumCariDetaylariResult
    {
        public object[] cO_ENTITY_BANK { get; set; }
        public Co_ENTITY_M[] cO_ENTITY_M { get; set; }
        public object[] cO_ENTITY_CONTACT { get; set; }
        public object[] cO_ENTITY_ADDRESS { get; set; }
    }

    public class Co_ENTITY_M
    {
        public string transportTypeIdSales { get; set; }
        public string transportTypeCodeSales { get; set; }
        public string transportTypeDescSales { get; set; }
        public string transporterIdSales { get; set; }
        public string transporterCodeSales { get; set; }
        public string transporterDescSales { get; set; }
        public string transportTypeIdPurchase { get; set; }
        public string transportTypeCodePurchase { get; set; }
        public string transportTypeDescPurchase { get; set; }
        public string identifyNo { get; set; }
        public string isVariousEntity { get; set; }
        public string id { get; set; }
        public string createUserId { get; set; }
        public string updateUserId { get; set; }
        public string createDate { get; set; }
        public string updateDate { get; set; }
        public string paymentMethodId { get; set; }
        public string paymentMethodId2 { get; set; }
        public string interCompanyCodeId { get; set; }
        public string interCompanyCode { get; set; }
        public string interCompanyDesc { get; set; }
        public string childCoId { get; set; }
        public string childCoCode { get; set; }
        public string childCoDesc { get; set; }
        public string childBranchId { get; set; }
        public string childBranchCode { get; set; }
        public string childBranchDesc { get; set; }
        public string paymentMethodCode { get; set; }
        public string paymentMethodDesc { get; set; }
        public string paymentMethodCode2 { get; set; }
        public string paymentMethodDesc2 { get; set; }
        public string incotermsId { get; set; }
        public string incotermsName { get; set; }
        public string incotermsCode { get; set; }
        public string domesticForeign { get; set; }
        public string incotermsId2 { get; set; }
        public string incotermsName2 { get; set; }
        public string incotermsCode2 { get; set; }
        public string eInvoiceProfile { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string mobileTel { get; set; }
        public string firstName { get; set; }
        public string familyName { get; set; }
        public string catCode1Id { get; set; }
        public string catCode2Id { get; set; }
        public string cityId { get; set; }
        public string countryId { get; set; }
        public string coId { get; set; }
        public string curTraId { get; set; }
        public string entityCode { get; set; }
        public string entityId { get; set; }
        public string entityName { get; set; }
        public string entityNameShort { get; set; }
        public string entityNote { get; set; }
        public string fax { get; set; }
        public string fax2 { get; set; }
        public string sectorId { get; set; }
        public string taxNo { get; set; }
        public string iseInvoiceEntity { get; set; }
        public string taxOfficeId { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string townId { get; set; }
        public string catCode1 { get; set; }
        public string catCode2 { get; set; }
        public string sectorCode { get; set; }
        public string cityName { get; set; }
        public string townName { get; set; }
        public string countryName { get; set; }
        public string curCode { get; set; }
        public string taxOfficeCode { get; set; }
        public string taxOfficeDesc { get; set; }
        public string coCode { get; set; }
        public string curId { get; set; }
        public string accId { get; set; }
        public string accCode { get; set; }
        public string cardIntgGrpId { get; set; }
        public string cardIntgGroupCode { get; set; }
        public string coEntityIntgCollection { get; set; }
        public string coEntityDiscCollection { get; set; }
        public string coEntityContactCollection { get; set; }
        public string coEntityAddressCollection { get; set; }
        public string coEntityB2BCollection { get; set; }
        public string agreementDate { get; set; }
        public string cashFlowInclusion { get; set; }
        public string curValution { get; set; }
        public string entityCodeOld { get; set; }
        public string entityGrp2Id { get; set; }
        public string entityGrp3Id { get; set; }
        public string entityGrpId { get; set; }
        public string entityType { get; set; }
        public string isblackList { get; set; }
        public string ispassive { get; set; }
        public string issendMail { get; set; }
        public string note1 { get; set; }
        public string entityGrpCode1 { get; set; }
        public string entityGrpName1 { get; set; }
        public string entityGrpCode2 { get; set; }
        public string entityGrpName2 { get; set; }
        public string entityGrpCode3 { get; set; }
        public string entityGrpName3 { get; set; }
        public string isnotPurchased { get; set; }
        public string isnotPOrder { get; set; }
        public string isnotSold { get; set; }
        public string isnotSOrder { get; set; }
        public string paymentPlanPId { get; set; }
        public string paymentPlanSId { get; set; }
        public string purchasePersonId { get; set; }
        public string salesPersonId { get; set; }
        public string curRateTypePId { get; set; }
        public string curRateTypeSId { get; set; }
        public string paymentPlanPCode { get; set; }
        public string paymentPlanSCode { get; set; }
        public string curRateTypePCode { get; set; }
        public string curRateTypeSCode { get; set; }
        public string salesPersonCode { get; set; }
        public string purchasePersonCode { get; set; }
        public string accDesc { get; set; }
        public string purchasePersonName { get; set; }
        public string paymentPlanPName { get; set; }
        public string salesPersonName { get; set; }
        public string paymentPlanSName { get; set; }
        public string dueDateBase { get; set; }
        public string dueDateControl { get; set; }
        public string priorityNo { get; set; }
        public string isMultiCur { get; set; }
        public string zipCode { get; set; }
        public string email { get; set; }
        public string webSite { get; set; }
        public string longtitude { get; set; }
        public string latitude { get; set; }
        public string dueDay { get; set; }
        public string dueDayPurchase { get; set; }
        public string optionDay { get; set; }
        public string coDesc { get; set; }
        public string entityPriceGrpPId { get; set; }
        public string entityPriceGrpSId { get; set; }
        public string entityPriceGrpPCode { get; set; }
        public string entityPriceGrpSCode { get; set; }
        public string sectorName { get; set; }
        public string entityPriceGrpPName { get; set; }
        public string entityPriceGrpSName { get; set; }
        public string riskGrpId { get; set; }
        public string riskGrpDesc { get; set; }
        public string riskGrpCode { get; set; }
        public string dueDiscId { get; set; }
        public string dueDiscCode { get; set; }
        public string dueDiscDesc { get; set; }
        public string curRateTypePDesc { get; set; }
        public string curRateTypeSDesc { get; set; }
        public string entityB2BCode { get; set; }
        public string parentEntityName { get; set; }
        public string parentEntityCode { get; set; }
        public string parentEntityId { get; set; }
        public string matchType { get; set; }
        public string approvalStatusId { get; set; }
        public string isEndUser { get; set; }
        public string approvalStatusCode { get; set; }
        public string requestStatus { get; set; }
        public string addDate01 { get; set; }
        public string addDate02 { get; set; }
        public string addDate03 { get; set; }
        public string addDate04 { get; set; }
        public string addDate05 { get; set; }
        public string addDate06 { get; set; }
        public string addDate07 { get; set; }
        public string addDate08 { get; set; }
        public string addDate09 { get; set; }
        public string addDate10 { get; set; }
        public string addDec01 { get; set; }
        public string addDec02 { get; set; }
        public string addDec03 { get; set; }
        public string addDec04 { get; set; }
        public string addDec05 { get; set; }
        public string addDec06 { get; set; }
        public string addDec07 { get; set; }
        public string addDec08 { get; set; }
        public string addDec09 { get; set; }
        public string addDec10 { get; set; }
        public string addString01 { get; set; }
        public string addString02 { get; set; }
        public string addString03 { get; set; }
        public string addString04 { get; set; }
        public string addString05 { get; set; }
        public string addString06 { get; set; }
        public string addString07 { get; set; }
        public string addString08 { get; set; }
        public string addString09 { get; set; }
        public string addString10 { get; set; }
        public string salesContactId { get; set; }
        public string purchaseContactId { get; set; }
        public string ibanPublic { get; set; }
        public string altCBalance { get; set; }
        public string cardIntgId { get; set; }
        public object cardIntgCode { get; set; }
        public object cardIntgDesc { get; set; }
        public string isNotInsertRiskLimit { get; set; }
        public string curTypeTranslation { get; set; }
        public string whouseId { get; set; }
        public string whouseCode { get; set; }
        public string whouseDesc { get; set; }
        public string consignedWhouseId { get; set; }
        public string consignedWhouseCode { get; set; }
        public string consignedWhouseDesc { get; set; }
        public object coEntityContactButton { get; set; }
        public object coEntityAccCodeButton { get; set; }
        public string isEmail { get; set; }
        public string isSms { get; set; }
        public string isTel { get; set; }
        public string eInvoicePartyIdentificationCollection { get; set; }
        public string entityBankCollection { get; set; }
        public string entityItemCollection { get; set; }
        public string modified { get; set; }
        public string senarioMod { get; set; }
        public string promptValue { get; set; }
        public string promptValues { get; set; }
        public string justUpdate { get; set; }
        public object controlProperties { get; set; }
        public object uyumObjectContainerCollection { get; set; }
        public string parent { get; set; }
        public string dynamicValues { get; set; }
        public string guid { get; set; }
        public string extendedObjects { get; set; }
    }

}